server:
  port: 8080
spring:
  application:
    name: husu-code-craftsman
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://124.222.255.211:3306/ricardo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
      initialSize: 10                                     # 初始化连接池大小
      minIdle: 5                                          # 最小
      maxActive: 20                                       # 最大
      maxWait: 60000                                      # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 3600000              # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 3600000                 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true                        # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      filters: stat                                       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙

springdoc:
  packagesToScan: com.husu
  swagger-ui:
    path: /swagger/index.html
    enabled: true
  api-docs:
    path: /swagger/api-docs
    enabled: true

mybatis:
   mapper-locations: classpath:/mapper/*.xml



